# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [16]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [17]:
#load csv file from weatherpy

filepath = "../Resources/cities.csv"
cities_df = pd.read_csv(filepath)

cities_df.head()

,City,Cloudiness,Country,Date,Humidity,Temp,Lat,Lng,Wind Speed
0,Santa Lucía,20,ES,10/18/2020,83,69.8,27.91,-15.54,8.05
1,Punta Arenas,40,CL,10/18/2020,70,42.8,-53.15,-70.92,31.09
2,Sri Aman,87,MY,10/18/2020,100,71.6,1.24,111.46,1.12
3,Ballina,75,AU,10/18/2020,100,63.0,-28.87,153.57,9.10
4,Longyearbyen,20,SJ,10/18/2020,73,26.6,78.22,15.64,8.05

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [18]:
gmaps.configure(api_key=g_key)

In [37]:
#Store locations

locations = cities_df[["Lat", "Lng"]].astype(float)

humidity = cities_df["Humidity"].astype(float)

home_loc = (37.09, -95.71)

In [40]:
fig = gmaps.figure(center= home_loc, zoom_level= 3)

#map.setOptions({ minZoom: 5, maxZoom: 15 })

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)


fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [41]:
# Create a dream vacation df fitting the weather conditions you prefer



#narrowed_city_df = cities.loc[(cities["Max Temp"] > 70) & (cities["Max Temp"] < 80) & (cities["Cloudiness"] == 0), :]
#narrowed_city_df = narrowed_city_df.dropna(how='any')
#narrowed_city_df.reset_index(inplace=True)

dream_vacay = cities_df.loc[(cities_df["Temp"] >= 75) & (cities_df["Temp"] <= 85) & (cities_df["Wind Speed"] <= 5) & (cities_df["Cloudiness"] <= 10), :]


dream_vacay= dream_vacay.dropna(how='any')
dream_vacay_df = pd.DataFrame(dream_vacay)
dream_vacay_df.reset_index(inplace=True)
dream_vacay_df

,index,City,Cloudiness,Country,Date,Humidity,Temp,Lat,Lng,Wind Speed
0,48,Santa Maria,0,BR,10/18/2020,56,78.64,-29.68,-53.81,4.68
1,82,Pala,0,TD,10/18/2020,52,78.53,9.36,14.90,3.51
2,175,Rancho Palos Verdes,5,US,10/18/2020,73,77.00,33.74,-118.39,4.70
3,188,Kousséri,0,CM,10/18/2020,65,82.40,12.08,15.03,1.12
4,201,Susanville,1,US,10/18/2020,22,79.00,40.42,-120.65,3.36
5,347,Berbera,0,SO,10/18/2020,51,84.87,10.44,45.01,2.01
6,400,Kiryat Gat,0,IL,10/18/2020,85,75.99,31.61,34.76,3.83
7,428,Madison,1,US,10/18/2020,50,77.00,34.73,-86.57,4.70
8,514,Dakar,0,SN,10/18/2020,89,84.20,14.69,-17.44,2.24

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [42]:
dream_vacay_df["Hotel Name"] = ""
dream_vacay_df.head()

,index,City,Cloudiness,Country,Date,Humidity,Temp,Lat,Lng,Wind Speed,Hotel Name
0,48,Santa Maria,0,BR,10/18/2020,56,78.64,-29.68,-53.81,4.68,
1,82,Pala,0,TD,10/18/2020,52,78.53,9.36,14.90,3.51,
2,175,Rancho Palos Verdes,5,US,10/18/2020,73,77.00,33.74,-118.39,4.70,
3,188,Kousséri,0,CM,10/18/2020,65,82.40,12.08,15.03,1.12,
4,201,Susanville,1,US,10/18/2020,22,79.00,40.42,-120.65,3.36,

In [43]:

# List of params
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

# Find nearby hotels using lat/lng
for index, row in dream_vacay_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while using same params
    params["location"] = f"{lat},{lng}"

    # Create base url
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make request
    name_address = requests.get(base_url, params=params)
    

    # Convert to json
    name_address = name_address.json()

    # Skip any that are missing data points.
    try:
        dream_vacay_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
        
        
        
    except (KeyError, IndexError, NameError):
        print("Missing field/result... skipping.")

hotel_df = pd.DataFrame(dream_vacay_df)        
        
hotel_df

,index,City,Cloudiness,Country,Date,Humidity,Temp,Lat,Lng,Wind Speed,Hotel Name
0,48,Santa Maria,0,BR,10/18/2020,56,78.64,-29.68,-53.81,4.68,Hotel Morotin
1,82,Pala,0,TD,10/18/2020,52,78.53,9.36,14.90,3.51,Hotel Pala Palace
2,175,Rancho Palos Verdes,5,US,10/18/2020,73,77.00,33.74,-118.39,4.70,Terranea Resort
3,188,Kousséri,0,CM,10/18/2020,65,82.40,12.08,15.03,1.12,Résidence le Palmier
4,201,Susanville,1,US,10/18/2020,22,79.00,40.42,-120.65,3.36,Red Lion Inn & Suites Susanville
5,347,Berbera,0,SO,10/18/2020,51,84.87,10.44,45.01,2.01,Damal Hotel
6,400,Kiryat Gat,0,IL,10/18/2020,85,75.99,31.61,34.76,3.83,OlusHome
7,428,Madison,1,US,10/18/2020,50,77.00,34.73,-86.57,4.70,Embassy Suites by Hilton Huntsville Hotel & Spa
8,514,Dakar,0,SN,10/18/2020,89,84.20,14.69,-17.44,2.24,Novotel Dakar

In [44]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

hotel_info

['\n<dl>\n<dt>Name</dt><dd>Hotel Morotin</dd>\n<dt>City</dt><dd>Santa Maria</dd>\n<dt>Country</dt><dd>BR</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Hotel Pala Palace</dd>\n<dt>City</dt><dd>Pala</dd>\n<dt>Country</dt><dd>TD</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Terranea Resort</dd>\n<dt>City</dt><dd>Rancho Palos Verdes</dd>\n<dt>Country</dt><dd>US</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Résidence le Palmier</dd>\n<dt>City</dt><dd>Kousséri</dd>\n<dt>Country</dt><dd>CM</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Red Lion Inn & Suites Susanville</dd>\n<dt>City</dt><dd>Susanville</dd>\n<dt>Country</dt><dd>US</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Damal Hotel</dd>\n<dt>City</dt><dd>Berbera</dd>\n<dt>Country</dt><dd>SO</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>OlusHome</dd>\n<dt>City</dt><dd>Kiryat Gat</dd>\n<dt>Country</dt><dd>IL</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Embassy Suites by Hilton Huntsville Hotel & Spa</dd>\n<dt>City</dt><dd>Madison</dd>\n<dt>Country</dt><dd>US</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Novotel Dakar</dd>\n<dt>City</dt><dd>Dakar</dd>\n<dt>Country</dt><dd>SN</dd>\n</dl>\n']

In [48]:
# Add marker layer ontop of heat map
hotel_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(hotel_layer)


# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [46]:
print("Bon Voyage!")

Bon Voyage!